workflows:
  android_native:
    name: Grocery Native APK
    max_build_duration: 60
    instance_type: mac_mini_m2    # build machine (can also be linux_x2)
    environment:
      groups:
        - firebase                # loads FIREBASE_JSON_B64
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$FIREBASE_JSON_B64" | base64 --decode > app/google-services.json
      - name: Build debug APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
