workflows:
  android_native:
    name: Grocery Native APK
    max_build_duration: 60
    environment:
      groups:
        - firebase        # 👈 this loads all variables from the "firebase" group in Codemagic UI
      android:
        image: latest
    scripts:
      - name: Decode google-services.json
        script: |
          # Decode the Firebase config from base64 and save into app/google-services.json
          echo "$FIREBASE_JSON_B64" | base64 --decode > app/google-services.json
      - name: Build debug APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
