workflows:
  android_native:
    name: Android (Gradle)
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Show Java/Gradle versions
        script: |
          java -version || true
          ./gradlew -v || true
      - name: Build debug APK
        script: ./gradlew --no-daemon :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
