workflows:
  android_native:
    name: Grocery Native APK
    max_build_duration: 60
    environment:
      groups:
        - firebase         # loads your FIREBASE_JSON_B64 var
      image: latest        # no "android:" block here
    scripts:
      - name: Decode google-services.json
        script: |
          echo "$FIREBASE_JSON_B64" | base64 --decode > app/google-services.json
      - name: Build debug APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
